function [pvalueutest, significancelevelutest, pvaluekstest, significancelevelkstest, pvaluettest, significancelevelttest] = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [PVALUEUTEST, SIGNIFICANCELEVELUTEST, PVALUEKSTEST,
%  SIGNIFICANCELEVELKSTEST, PVALUETTEST, SIGNIFICANCELEVELTTEST] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [PVALUEUTEST, SIGNIFICANCELEVELUTEST, PVALUEKSTEST,
%  SIGNIFICANCELEVELKSTEST, PVALUETTEST, SIGNIFICANCELEVELTTEST] =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [pvalueutest, significancelevelutest, pvaluekstest, significancelevelkstest, pvaluettest, significancelevelttest] = importfile1("C:\Users\scontreras\Dropbox\Trabajo\CEBIB\Proyectos pendientes\Paper muestreo\mFiles\Fig_1_Statistical_analysis\results_new_process\exp_1_k_25\results_comparison.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2022 10:49:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "pvalueutest", "significancelevelutest", "Var5", "pvaluekstest", "significancelevelkstest", "Var8", "pvaluettest", "significancelevelttest"];
opts.SelectedVariableNames = ["pvalueutest", "significancelevelutest", "pvaluekstest", "significancelevelkstest", "pvaluettest", "significancelevelttest"];
opts.VariableTypes = ["string", "string", "double", "string", "string", "double", "categorical", "string", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "significancelevelutest", "Var5", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "significancelevelutest", "Var5", "significancelevelkstest", "Var8", "significancelevelttest"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
pvalueutest = tbl.pvalueutest;
significancelevelutest = tbl.significancelevelutest;
pvaluekstest = tbl.pvaluekstest;
significancelevelkstest = tbl.significancelevelkstest;
pvaluettest = tbl.pvaluettest;
significancelevelttest = tbl.significancelevelttest;
end